
// This file can be used to define custom types that are not auto-generated by Supabase.

// Customer Types
export type CustomerStatus =
  | "new_contact"
  | "appointment_set"
  | "quotation_sent"
  | "follow_up"
  | "active_client"
  | "closed";

export type CustomerSource =
  | "instagram"
  | "whatsapp"
  | "referral"
  | "website"
  | "advertisement"
  | "other";

export interface Customer {
  id: string;
  name: string;
  phone: string;
  email?: string | null;
  source: CustomerSource;
  city?: string | null;
  country?: string | null;
  business_type?: string | null;
  status: CustomerStatus;
  assigned_to?: string | null;
  notes?: string | null;
  reason_closed?: string | null;
  created_at: string;
  updated_at: string;
  assigned_user?: {
    id: string;
    name: string;
    email: string;
  } | null;
}

// Meeting Types
export type MeetingType = "in_person" | "online" | "phone";

export interface Meeting {
  id: string;
  customer_id: string;
  meeting_date: string;
  meeting_type: MeetingType;
  purpose?: string | null;
  summary?: string | null;
  attachments?: string | null;
  created_at: string;
  customer?: {
    id: string;
    name: string;
  } | null;
}

// Quotation Types
export type QuotationStatus = "sent" | "accepted" | "rejected" | "draft";

export interface Quotation {
  id: string;
  customer_id: string;
  quotation_no: string;
  send_date?: string | null;
  amount: number;
  currency: string;
  services: string[];
  status: QuotationStatus;
  validity_date?: string | null;
  reason?: string | null;
  created_at: string;
  customer?: {
    id: string;
    name: string;
    phone?: string | null;
  } | null;
}

// Follow-up Types
export type FollowupMethod = "call" | "whatsapp" | "email" | "meeting";

export interface Followup {
  id: string;
  customer_id: string;
  followup_date: string;
  method: FollowupMethod;
  notes: string;
  next_followup?: string | null;
  is_done: boolean;
  assigned_to?: string | null;
  created_at: string;
  customer?: {
    id: string;
    name: string;
  } | null;
}

// Service Types
export interface Service {
  id: string;
  name: string;
  description?: string | null;
  is_active: boolean;
  created_at: string;
}

export interface CustomerService {
  id: string;
  customer_id: string;
  service_id: string;
  start_date: string;
  status: "active" | "completed" | "paused";
  notes?: string | null;
  created_at: string;
  service?: {
    id: string;
    name: string;
    description?: string | null;
  }
}

// User Types
export type UserRole = "admin" | "manager" | "sales" | "employee";

export interface User {
  id: string;
  full_name: string;
  email: string;
  role: UserRole;
  created_at: string;
}

export const EMPLOYEE_ROLES = {
  admin: "admin",
  manager: "manager",
  sales: "sales",
  employee: "employee",
} as const;

export const EMPLOYEE_ROLE_LABELS: Record<UserRole, string> = {
  admin: "مدير",
  manager: "مدير فريق",
  sales: "مبيعات",
  employee: "موظف",
};

// Activity Types
export type ActivityType =
  | "customer_created"
  | "customer_updated"
  | "meeting_scheduled"
  | "meeting_completed"
  | "quotation_sent"
  | "quotation_accepted"
  | "quotation_rejected"
  | "followup_scheduled"
  | "followup_completed"
  | "status_changed"
  | "service_added"
  | "service_updated";

export interface Activity {
  id: string;
  customer_id: string;
  type: ActivityType;
  description: string;
  created_by?: string | null;
  created_at: string;
}
