// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqrerbbkjtagfndpgnei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxcmVyYmJranRhZ2ZuZHBnbmVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2OTkyMzIsImV4cCI6MjA3ODI3NTIzMn0.DmlVfMmOdsgCZPWCNL4uQbv6peMFcc_0TbddJvT9c2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
